.PHONY: install
install:
	cp --update=none .env.example .env
	pip install --require-virtualenv --upgrade pip
	pip install --require-virtualenv -e ".[dev]"
	pre-commit install

.PHONY: lock
lock:
	pip-compile -o requirements.txt pyproject.toml

.PHONY: update
update:
	copier update --vcs-ref=$(tag) .

.PHONY: generate
generate:
	docker run --rm \
	--user $$(id -u):$$(id -g) \
	-v ${PWD}:/local openapitools/openapi-generator-cli generate \
	-i /local/openapi.yaml \
	-g python-fastapi \
	--package-name {{ project_name }} \
	-o /local
	mv src/{{ project_name }}/* {{ project_name }}/
	rm -r src

.PHONY: run
run:
	set -a && . .env && set +a && uvicorn {{ project_name }}.main:app --host 0.0.0.0 --port 8080 --reload

{% if storage -%}
.PHONY: migrate
migrate:
	alembic upgrade head

.PHONY: revision
revision:
	alembic ensure_version
	alembic revision --autogenerate -m $(message)$(m)
{% endif %}
